# app/api/api_v1/api.py
from fastapi import APIRouter

# --- Import endpoint routers ---
# Each module in /endpoints defines routes for a specific domain (stats, meters, auth, etc.)
from .endpoints import stats, meters, auth  # Add new endpoint modules here as needed

# --- Create main API router ---
# This central router groups all sub-routers and will be included in main.py
api_router = APIRouter()

# --- Register sub-routers ---
# Each include_router call mounts a group of related endpoints under a specific URL prefix
# 'tags' help organize and group endpoints in the autogenerated Swagger docs

api_router.include_router(
    stats.router,        # Router object from stats.py
    prefix="/stats",     # All stats endpoints will be under /api/v1/stats
    tags=["stats"]       # Tag name in Swagger UI
)

api_router.include_router(
    meters.router,       # Router object from meters.py
    prefix="/meters",    # All meter endpoints will be under /api/v1/meters
    tags=["meters"]
)

api_router.include_router(
    auth.router,         # Router object from auth.py
    prefix="/auth",      # All auth endpoints will be under /api/v1/auth
    tags=["auth"]
)
